apiVersion: "auth.casbin.org/v1"
kind: CasbinModel
metadata:
  name: allowed-repo
  namespace: policy
spec:
  modelText: |
    [request_definition]
    r = namespace,image
    
    [policy_definition]
    p = namespace,image,eft
    
    [policy_effect]
    e =some(where (p.eft == allow))
    
    [matchers]
    m = r.namespace == p.namespace && hasPrefix(r.image, p.image)
  

  