# permissions for end users to view casbinmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: casbinmodel-viewer-role
rules:
- apiGroups:
  - auth.casbin.org
  resources:
  - casbinmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.casbin.org
  resources:
  - casbinmodels/status
  verbs:
  - get
