apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  ##EDIT HERE
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: required-labels.stable.example.com
  namespace: policy
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                policyItem:
                  ##EDIT HERE
                  #this policyItem contains a line of policy. multiple lines of policy is forbiddened
                  type: string
                
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    ## EDIT HERE: change the plural,singular and kind of the name to your own policy name.
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: required-labels
    # singular name to be used as an alias on the CLI and for display
    singular: required-labels
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: RequiredLabels
    # shortNames allow shorter string to match your resource on the CLI
    # shortNames:
    # - pl