apiVersion: "auth.casbin.org/v1"
kind: CasbinModel
metadata:
  name: required-labels
  namespace: policy
spec:
  associatedPolicyCrdPlural: required-labels
  modelText: |
    [request_definition]
    r = k,v
    
    [policy_definition]
    p = k,v,eft
    
    [policy_effect]
    e =some(where (p.eft == allow))
    
    [matchers]
    m = r.k == p.k && regexMatch(r.v,p.v)
  

  