apiVersion: "auth.casbin.org/v1"
kind: CasbinModel
metadata:
  name: disallowed-tags
  namespace: kubesphere-authz-system
spec:
  associatedPolicyCrdPlural: disallowed-tags
  modelText: |
    [request_definition]
    r = namespace,tag
    
    [policy_definition]
    p = namespace,tag,eft
    
    [policy_effect]
    e =!some(where (p.eft == deny))
    
    [matchers]
    m = r.namespace == p.namespace && r.tag==p.tag
  

  