apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo-disallowed
spec:
  tls:
    - hosts:
      - example-host.example.com
  rules:
    - host: example-host.example.com
      http:
        paths:
          - backend:
              service:
                name: nginx
                port:
                  number: 80
            pathType: Exact
            path: /